/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.tcc.visao;

import javax.swing.JDialog;

/**
 *
 * @author macel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        sbmFuncionario = new javax.swing.JMenuItem();
        sbmSentenciado = new javax.swing.JMenuItem();
        sbmCoordenadoria = new javax.swing.JMenuItem();
        sbmPresidio = new javax.swing.JMenuItem();
        sbmPavilhao = new javax.swing.JMenuItem();
        sbmOcorrencia = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        sbmMovimentacaoPorPeriodo = new javax.swing.JMenuItem();
        sbmSistema = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas - Tela Principal");
        setExtendedState(6);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fundo.jpg"))); // NOI18N

        menuCadastro.setText("Cadastro");
        menuCadastro.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        sbmFuncionario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sbmFuncionario.setText("Funcionário");
        sbmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmFuncionario);

        sbmSentenciado.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmSentenciado.setText("Sentenciado");
        sbmSentenciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmSentenciadoActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmSentenciado);

        sbmCoordenadoria.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmCoordenadoria.setText("Coordenadoria");
        sbmCoordenadoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmCoordenadoriaActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmCoordenadoria);

        sbmPresidio.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmPresidio.setText("Presidio");
        sbmPresidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmPresidioActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmPresidio);

        sbmPavilhao.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmPavilhao.setText("Pavilhão");
        sbmPavilhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmPavilhaoActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmPavilhao);

        sbmOcorrencia.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmOcorrencia.setText("Facção");
        sbmOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmOcorrenciaActionPerformed(evt);
            }
        });
        menuCadastro.add(sbmOcorrencia);

        jMenuBar1.add(menuCadastro);

        jMenu1.setText("Movimentação");
        jMenu1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuItem4.setText("Movimentação Internas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuItem5.setText("Movimentação Externas");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ocorrências");
        jMenu3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuItem1.setText("Sindicancias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuItem2.setText("Observações");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuItem3.setText("Eventos Coletivos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        sbmMovimentacaoPorPeriodo.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmMovimentacaoPorPeriodo.setText("Movimentação por Periodo");
        menuRelatorios.add(sbmMovimentacaoPorPeriodo);

        sbmSistema.setText("Sistema");
        sbmSistema.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        menuRelatorios.add(sbmSistema);

        jMenuBar1.add(menuRelatorios);

        jMenu4.setText("Sair");
        jMenu4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(915, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmServidorActionPerformed
//     //new DialogDadosServidor().setVisible(true);
//        FormServidor form = new FormServidor(this, true);
//        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//        form.setTitle("Manutenção do Servidor");
//        form.setLocationRelativeTo(null);
//        form.setResizable(false);
//        form.setVisible(true);
    }//GEN-LAST:event_sbmServidorActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void sbmOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmOcorrenciaActionPerformed
        // TODO add your handling code here:
        FormularioFaccao fa = new FormularioFaccao(this, true);
        fa.setVisible(true);
    }//GEN-LAST:event_sbmOcorrenciaActionPerformed

    private void sbmPavilhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmPavilhaoActionPerformed
        // TODO add your handling code here:
        FormularioPavilhao pav = new FormularioPavilhao(this, true);
        pav.setVisible(true);
    }//GEN-LAST:event_sbmPavilhaoActionPerformed

    private void sbmPresidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmPresidioActionPerformed
        // TODO add your handling code here:
        FormularioPresidio pre = new FormularioPresidio(this, true);
        pre.setVisible(true);
    }//GEN-LAST:event_sbmPresidioActionPerformed

    private void sbmCoordenadoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmCoordenadoriaActionPerformed
        // TODO add your handling code here:
        FormularioCoordenadoria c = new FormularioCoordenadoria(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_sbmCoordenadoriaActionPerformed

    private void sbmSentenciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmSentenciadoActionPerformed
        // TODO add your handling code here:
        FormularioSentenciado f = new FormularioSentenciado(this, true);
        f.setVisible(true);

    }//GEN-LAST:event_sbmSentenciadoActionPerformed

    private void sbmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmFuncionarioActionPerformed
        // TODO add your handling code here:
        FormularioFuncionario c = new FormularioFuncionario(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_sbmFuncionarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormularioSindicancia fs = new FormularioSindicancia(this, true);
        fs.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormularioObservacao fo = new FormularioObservacao(this, true);
        fo.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FormularioEventoColetivo fec = new FormularioEventoColetivo(this, true);
        fec.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem sbmCoordenadoria;
    private javax.swing.JMenuItem sbmFuncionario;
    private javax.swing.JMenuItem sbmMovimentacaoPorPeriodo;
    private javax.swing.JMenuItem sbmOcorrencia;
    private javax.swing.JMenuItem sbmPavilhao;
    private javax.swing.JMenuItem sbmPresidio;
    private javax.swing.JMenuItem sbmSentenciado;
    private javax.swing.JMenu sbmSistema;
    // End of variables declaration//GEN-END:variables
}
